### ISSUE TITLE
Verification in Challenge 4 (GitHubbin) does not complete.

### ISSUE THREAD

**Issue by samanthakem** [jlord/git-it-electron#164] opened 2016-09-28 20:57 UTC
I followed all the steps. Verification is taking too long (see gif below) and does not complete.

![git-it](https://cloud.githubusercontent.com/assets/4277045/18931951/41055334-8583-11e6-8f9c-4288756fd97f.gif)

**Comment by aw-kris** [comment] 2016-10-02 23:12
bump, the same thing happened for me too

**Comment by An3bi** [comment] 2016-10-03 23:33
I opened an issue here #166 and discovered you have the same problem.
Did you find a fix yet? @samanthakem

**Comment by rafaelferreiraql** [comment] 2016-10-14 17:59
Same here...

**Comment by jewelsjacobs** [comment] 2016-10-15 02:04
Me too.

**Comment by ZlateTheodor** [comment] 2016-10-15 17:13
Same here (Windows)

**Comment by willismonroe** [comment] 2016-10-15 17:15
The workaround is posted in this issue: https://github.com/jlord/git-it-electron/issues/160

**Comment by jlord** [comment] 2016-10-16 02:37
I've added a new version that fixes the missing dependency (don't know why it was't bundled to begin with...) here: https://github.com/jlord/git-it-electron/releases/tag/4.2.2 🍍 

Dupe of #160

**Closed by jlord** 2016-10-16 02:37 UTC
Labels: ℬ∪Ɠ ☹
